require('configs.auto_commands')
require('configs.completions')
require('configs.filer')
require('configs.galaxyline')
require('configs.general_functions')
require('configs.gits')
require('configs.startify')
require('configs.telescope')
